planning_main:
    resource: "@PlanningMainBundle/Resources/config/routing.yml"
    prefix:   /

planning_user:
    resource: "@PlanningUserBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
