client_index:
    path:     /
    defaults: { _controller: "PlanningMainBundle:Client:index" }
    methods:  GET

client_show:
    path:     /{id}/show
    defaults: { _controller: "PlanningMainBundle:Client:show" }
    methods:  GET

client_new:
    path:     /new
    defaults: { _controller: "PlanningMainBundle:Client:new" }
    methods:  [GET, POST]

client_edit:
    path:     /{id}/edit
    defaults: { _controller: "PlanningMainBundle:Client:edit" }
    methods:  [GET, POST]

client_delete:
    path:     /{id}/delete
    defaults: { _controller: "PlanningMainBundle:Client:delete" }
    methods:  DELETE
